# 8004表示Consul服务端口号
server:
  port: 8004

# 服务别名:注册到Consul注册中心的名称
spring:
  application:
    name: consul-payment-service
  cloud:
    consul:
      # Consul注册中心地址
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}