server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能,利用微服务名进行路由
          enabled: true
      routes:
          # 路由的ID,唯一
        - id: payment-routh
          # 匹配后提供服务的路由地址
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service
          # 过滤器
          filters:
            # 过滤器工厂会在匹配的请求头加一对请求头[X-Request-Id:1024]
            - AddRequestParameter=MyParam,MyParam_1024
            - AddRequestHeader=MyHeader,MyHeader_1024
          # 断言,路径相匹配的进行路由
          predicates:
            - Path=/payment/get/**
            - Method=GET,POST

        - id: payment-routh2
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

        - id: payment-routh3
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/discovery/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/